# Generated by Django 3.1.2 on 2020-10-18 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('index', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('location_prec', models.TextField(default='')),
                ('container', models.TextField(default='')),
                ('category', models.TextField(default='Sonstiges')),
                ('brand', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('store', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('history', models.TextField(default='')),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 10, 18, 22, 37, 7, 338076), verbose_name='Timestamp of report creation')),
                ('devices', models.IntegerField(verbose_name='Amount of devices in report')),
                ('query', models.TextField(default='', verbose_name='query for selected devices')),
                ('tex', models.TextField()),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
    ]
