# Generated by Django 3.1.2 on 2020-10-18 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 21, 41, 59, 91561, tzinfo=utc), verbose_name='Timestamp of report creation'),
        ),
    ]
