#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check failed. Run yarn format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check-Lint failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'ESLint Check-Types failed. Fix the problems, add changes and try to commit again.'
    false;
)


echo 'Static Checks passed, trying to build...'

npm run build ||
(
    echo 'Next build failed: View the errors above to see why.'
    false;
)


echo 'Checks and Build passed, commit went through.'