#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx pretty-quick --staged

# Check ESLint Standards
yarn check-lint ||
(
    echo 'ESLint Check-Lint failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo 'ESLint Check-Types failed. Fix the problems, add changes and try to commit again.'
    false;
)


echo 'Static Checks passed, trying to build...'

yarn build ||
(
    echo 'Next build failed: View the errors above to see why.'
    false;
)


echo 'Checks and Build passed, commit went through.'